package com.huahong.tolerant.orm.dao;


import com.huahong.tolerant.orm.model.Hr;
import com.huahong.tolerant.orm.model.HrExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface HrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbggenerated
     */
    int countByExample(HrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbggenerated
     */
    int deleteByExample(HrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbggenerated
     */
    int insert(Hr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbggenerated
     */
    int insertSelective(Hr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbggenerated
     */
    List<Hr> selectByExample(HrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbggenerated
     */
    Hr selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Hr record, @Param("example") HrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Hr record, @Param("example") HrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Hr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Hr record);

    Hr selectOne();
}