spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer
      auto-offset-reset: latest
  datasource:
    url: jdbc:mysql://localhost:3306/vhr?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 123456