spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer
      auto-offset-reset: latest
  datasource:
    url: jdbc:mysql://localhost:3306/vhr?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    # 打印sql, 方便调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
    default-statement-timeout: 60
    #interceptors: com.huahong.tolerant.join.interceptor.mybatis.SqlStatementInterceptor
  type-aliases-package: com.huahong.tolerant.join.domain
 # config-location: classpath*:/config/mybatis-config.xml